// data.jsx — shared sample data for DaniBOD ZZZ Analytics mockups
// 5 example PJs from brief + sets + 24 sample discs

const PJS = {
  yanagi:  { id: "yanagi",  name: "Yanagi",  ico: "assets/yanagi-ico.webp",  ext: "assets/yanagi-extend.webp",
             elem: "Eléctrico", role: "Anomalía", mind: 0, faction: "Section 6", factionLogo: "assets/faction-section6.webp",
             engine: "Llanto mielgo", engineR: 1, engineLogo: "assets/engine-llanto-mielgo.webp",
             set4: "Jazz Caótico", set2: "Blues Libre",
             stats: { pv: 10680, atk: 2690, cr: 21.8, cd: 64.4, anom: 329, er: 1.20, def: 950, impact: 92, bonus: "Bono Eléctrico 28%" },
             palette: { p: "#1E3A8A", s: "#7C3AED", t: "#0F172A" },
             elemColor: "#C5A8FF",
             buildPct: 87 },
  ellen:   { id: "ellen",   name: "Ellen",   ico: "assets/ellen-ico.webp",  ext: "assets/ellen-extend.webp",
             elem: "Hielo", role: "Ataque", mind: 0, faction: "Victoria", factionLogo: "assets/faction-victoria.webp",
             engine: "Visitante altamar", engineR: 1, engineLogo: "assets/engine-visitante-altamar.webp",
             set4: "Puffer Electro", set2: "Balada rama",
             stats: { pv: 11248, atk: 2667, cr: 72.2, cd: 171.6, anom: 89, er: 1.10, def: 880, impact: 88, bonus: "Bono Hielo 30%" },
             palette: { p: "#DC2626", s: "#0A0A0A", t: "#F5F5F5" },
             elemColor: "#9DE0F0",
             buildPct: 94 },
  yixuan:  { id: "yixuan",  name: "Yixuan",  ico: "assets/yixuan-ico.webp", ext: "assets/yixuan-extend.webp",
             elem: "Éter", role: "Disruptivo", mind: 0, faction: "Yunkui", factionLogo: "assets/faction-yunkui.webp",
             engine: "Caldero claridad", engineR: 1, engineLogo: "assets/engine-caldero-claridad.webp",
             set4: "Fábula Yunkui", set2: "Balada rama",
             stats: { pv: 17245, atk: 1907, cr: 65.0, cd: 162.0, anom: 110, er: 1.30, def: 1024, impact: 130, bonus: "Bono Éter 30% (Sheer)" },
             palette: { p: "#D4AF37", s: "#0A0A0A", t: "#8B6914" },
             elemColor: "#FF4D8A",
             buildPct: 76 },
  burnice: { id: "burnice", name: "Burnice", ico: "assets/burnice-ico.webp", ext: "assets/burnice-extend.webp",
             elem: "Fuego", role: "Anomalía", mind: 0, faction: "Sons of Calydon", factionLogo: "assets/faction-calydon.webp",
             engine: "Coctelera", engineR: 3, engineLogo: "assets/engine-coctelera.webp",
             set4: "Jazz Caótico", set2: "Blues Libre",
             stats: { pv: 10674, atk: 2601, cr: 14.0, cd: 50.0, anom: 398, er: 1.56, def: 920, impact: 96, bonus: "Bono Fuego 30%" },
             palette: { p: "#FF6B47", s: "#FFCB05", t: "#7A1F0F" },
             elemColor: "#FF7A45",
             buildPct: 91 },
  caesar:  { id: "caesar",  name: "Caesar",  ico: "assets/caesar-ico.webp", ext: "assets/caesar-extend.webp",
             elem: "Físico", role: "Defensa", mind: 2, faction: "Sons of Calydon", factionLogo: "assets/faction-calydon.webp",
             engine: "Proyector", engineR: 5, engineLogo: "assets/engine-proyector.webp",
             set4: "Punk Primitivo", set2: "Sacudestrellas",
             stats: { pv: 13155, atk: 1891, cr: 48.2, cd: 78.8, anom: 95, er: 1.20, def: 1256, impact: 170, bonus: "M2 · Impact +35" },
             palette: { p: "#FFCB05", s: "#D4AF37", t: "#0A0A0A" },
             elemColor: "#FFD66B",
             buildPct: 82 },
};

const SETS = {
  jazz:    { name: "Jazz Caótico",   logo: "assets/set-jazz-caotico.webp",   archetype: "ANOMALY" },
  blues:   { name: "Blues Libre",    logo: "assets/set-blues-libre.webp",    archetype: "ANOMALY" },
  puffer:  { name: "Puffer Electro", logo: "assets/set-puffer-electro.webp", archetype: "ATK_DPS" },
  balada:  { name: "Balada rama",    logo: "assets/set-balada-rama.webp",    archetype: "ATK_DPS" },
  fabula:  { name: "Fábula Yunkui",  logo: "assets/set-fabula-yunkui.webp",  archetype: "HP_DISRUPT" },
  punk:    { name: "Punk Primitivo", logo: "assets/set-punk-primitivo.webp", archetype: "DEFENSE" },
  sacude:  { name: "Sacudestrellas", logo: "assets/set-sacudestrellas.webp", archetype: "DEFENSE" },
};

// 24 sample discs spanning sets/slots/scores/states
const DISCS = [
  { id: "00482", set: "jazz",   slot: 4, main: "ATK% 30.0%",       subs: "CR×3 · CD×2 · ATK×1 · AnomM×2", lvl: 15, score: 87.3, tier: "S", pj: "yanagi",  state: "equipped",  hi: true },
  { id: "00471", set: "puffer", slot: 5, main: "DMG Eléc 30%",     subs: "CR×2 · ATK%×1 · HP×1",          lvl: 9,  score: 76.8, tier: "S", pj: "burnice", state: "equipped" },
  { id: "00465", set: "jazz",   slot: 6, main: "Maestría Anom 32", subs: "Anom×2 · ATK×1 · CR×1",         lvl: 3,  score: 62.4, tier: "A", pj: null,      state: "loose" },
  { id: "00463", set: "sacude", slot: 2, main: "DEF% 20%",          subs: "DEF×2 · HP×1",                  lvl: 15, score: 23.1, tier: "B", pj: null,      state: "discarded" },
  { id: "00521", set: "jazz",   slot: 4, main: "ATK% 30.0%",       subs: "CR×2 · CD×1 · AnomM×1",         lvl: 12, score: 79.0, tier: "S", pj: "burnice", state: "equipped" },
  { id: "00638", set: "jazz",   slot: 4, main: "ATK% 30.0%",       subs: "CR×3 · CD×1 · AnomM×2",         lvl: 15, score: 84.1, tier: "S", pj: null,      state: "loose" },
  { id: "00598", set: "balada", slot: 6, main: "Bono Hielo 30%",   subs: "CR×3 · CD×2 · ATK%×1",          lvl: 15, score: 91.2, tier: "S", pj: "ellen",   state: "equipped" },
  { id: "00611", set: "balada", slot: 5, main: "DMG Hielo 30%",    subs: "CR×2 · CD×2 · ATK×1",           lvl: 15, score: 88.5, tier: "S", pj: "ellen",   state: "equipped" },
  { id: "00422", set: "fabula", slot: 4, main: "HP% 30%",           subs: "HP×3 · DEF×1 · CR×1",           lvl: 12, score: 81.7, tier: "S", pj: "yixuan",  state: "equipped" },
  { id: "00415", set: "fabula", slot: 5, main: "DMG Éter 30%",      subs: "CR×2 · CD×2 · HP×1",            lvl: 15, score: 89.3, tier: "S", pj: "yixuan",  state: "equipped" },
  { id: "00388", set: "punk",   slot: 2, main: "DEF% 20%",          subs: "DEF×3 · Impact×1 · HP×1",       lvl: 15, score: 78.4, tier: "S", pj: "caesar",  state: "equipped" },
  { id: "00391", set: "sacude", slot: 6, main: "Impacto 18%",       subs: "Impact×2 · DEF×2 · HP×1",       lvl: 15, score: 74.6, tier: "S", pj: "caesar",  state: "equipped" },
  { id: "00510", set: "blues",  slot: 1, main: "HP plano",          subs: "HP×2 · ATK%×1 · AnomM×1",       lvl: 9,  score: 68.2, tier: "A", pj: "yanagi",  state: "equipped" },
  { id: "00509", set: "blues",  slot: 3, main: "ATK plano",         subs: "ATK%×2 · CR×1 · AnomM×2",       lvl: 12, score: 71.4, tier: "S", pj: "yanagi",  state: "equipped" },
  { id: "00488", set: "jazz",   slot: 1, main: "HP plano",          subs: "HP×2 · CR×1 · CD×1",            lvl: 6,  score: 54.0, tier: "A", pj: "burnice", state: "equipped" },
  { id: "00501", set: "jazz",   slot: 3, main: "ATK plano",         subs: "AnomM×3 · ATK%×1",              lvl: 12, score: 73.9, tier: "S", pj: "burnice", state: "equipped" },
  { id: "00345", set: "puffer", slot: 3, main: "ATK plano",         subs: "CR×3 · CD×1 · ATK%×1",          lvl: 15, score: 82.6, tier: "S", pj: "ellen",   state: "equipped" },
  { id: "00350", set: "puffer", slot: 1, main: "HP plano",          subs: "HP×2 · CR×2",                   lvl: 12, score: 67.5, tier: "A", pj: "ellen",   state: "equipped" },
  { id: "00298", set: "fabula", slot: 1, main: "HP plano",          subs: "HP×3 · DEF×1 · ER×1",           lvl: 12, score: 70.2, tier: "S", pj: "yixuan",  state: "equipped" },
  { id: "00302", set: "fabula", slot: 3, main: "ATK plano",         subs: "HP%×2 · CD×1 · CR×2",           lvl: 15, score: 77.8, tier: "S", pj: "yixuan",  state: "equipped" },
  { id: "00277", set: "punk",   slot: 5, main: "DMG Físico 30%",    subs: "DEF×2 · Impact×2 · HP×1",       lvl: 12, score: 66.1, tier: "A", pj: "caesar",  state: "equipped" },
  { id: "00250", set: "balada", slot: 2, main: "ATK% 25%",          subs: "CR×2 · CD×2 · ATK×1",           lvl: 9,  score: 58.7, tier: "A", pj: null,      state: "loose" },
  { id: "00244", set: "blues",  slot: 6, main: "Maestría Anom 32",  subs: "Anom×3 · ATK×2",                lvl: 12, score: 69.8, tier: "A", pj: null,      state: "loose" },
  { id: "00198", set: "punk",   slot: 4, main: "DEF% 20%",          subs: "HP%×1 · DEF×2",                 lvl: 6,  score: 31.2, tier: "B", pj: null,      state: "discarded" },
];

Object.assign(window, { PJS, SETS, DISCS });
